#application:
#  bot:
#    user:
#      name:
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:c:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect