CREATE TABLE QUESTION (
QUE_IDENT VARCHAR(50) NOT NULL,
QUE_MESSA VARCHAR(200) NOT NULL,
PRIMARY KEY(QUE_IDENT)
);

CREATE TABLE BUTTON (
BUT_IDENT VARCHAR(50) NOT NULL,
QUE_IDENT VARCHAR(50) NOT NULL,
PRIMARY KEY(BUT_IDENT)
);


-- INITIAL DATA

INSERT INTO QUESTION (QUE_IDENT, QUE_MESSA) VALUES ('question1', '.....');
INSERT INTO QUESTION (QUE_IDENT, QUE_MESSA) VALUES ('start', '¿Está segur@ que desea iniciar?');